const String SEARCH_USER_LIST_LOADING = 'SEARCH_USER_LIST_LOADING';
const String SEARCH_USER_LIST_SUCCESS = 'SEARCH_USER_LIST_SUCCESS';
const String SEARCH_USER_LIST_FAILURE = 'SEARCH_USER_LIST_FAILURE';
